### ISSUE TITLE
Versions-System einführen

### ISSUE THREAD

**Issue by carlobeltrame** [gloggi/qualix#108]
* SemVer Releases
* Changelog / Release notes
* What's new auf Welcome Seite

**Comment by cleverer** [comment]
Würde mich freuen, wenn dieses Issue bald angegangen wird, da ich momentan die commits durchgehe und unserem Ausbildungsverantwortlichen Bescheid gebe, was geändert wurde. Wenn es bereits ein Changelog gäbe, wäre das natürlich einfacher 😉

**Comment by carlobeltrame** [comment]
Lindo arbeitet daran, die letzten Änderungen auf der Startseite anzuzeigen. Diese müssen aber eben immer auch übersetzt werden, was das ganze leicht komplizierter macht. Wir haben jedenfalls schon mal die bemerkbaren neuen Features seit April 2019 rausgesucht:
- Multi TN Beobachtungen
- Import von Blöcken aus eCamp v2
- Archivierung und Löschung von Kursen
- Wiederherstellung von Formulareingaben nach automatischem Logout wegen Timeout
- MiData-Login
- Tagesspick
- Hilfetexte
- Übersetzung auf Französisch

**Comment by cleverer** [comment]
Das Anzeigen im Qualix selbst wäre für mich eher optional, viel wichtiger fände ich ein einfaches CHANGELOG.md im Repo und jeweilige Git Tags/Github Releases.

**Comment by carlobeltrame** [comment]
Changelog existiert nun seit längerem, und auf der Willkommens-Seite wird dorthin verlinkt (halt nur auf deutsch). SemVer halte ich aktuell für eher weniger sinnvoll, da die Definition von "breaking change" für Nutzende [schwierig](https://xkcd.com/1172/) ist.
