### ISSUE TITLE
Beobachtungsaufträge

### ISSUE THREAD

**Issue by carlobeltrame** [gloggi/qualix#115]
* Beobachtungsauftrag ist eine neue Entity.
* Ein Beobachtungsauftrag gehört zu genau einer Leitungsperson und einem/r TN und einem Block.
* Beim Erstellen von einem Beobachtungsauftrag kann man aber mehrere Blöcke gleichzeitig auswählen (Multiselect) in denen der Beobachtungsauftrag erstellt werden soll. Es wird für jeden ausgewählten Block ein unabhängiger Beobachtungsauftrag erstellt.
* Es soll auf dem Formular die Möglichkeit geben, alle Blöcke an einem Tag oder alle Blöcke in einem Ausbildungsgefäss auszuwählen (ähnlich wie TN-Gruppen Presets funktionieren sollen)
* Auf dem Spick soll bei jedem Block angezeigt werden, welche TN ich (eingeloggter User) im Block beobachten muss.
  * Name + Bild mit farbigem Rand um anzuzeigen ob ich schon eine Beobachtung im Block für den/die TN gemacht habe (irgendeine reicht).
  * Klick auf TN öffnet Beobachtungsformular mit Block und TN vorausgewählt

**Comment by carlobeltrame** [comment]
Use case Tetra:
> Zuteilung der Leiter von TN auf Blöcke:
> Ich möchte gerne sehen, welche Beobachtungen noch offen sind. In einem Ausbildungsgefäss ist schon im Voraus klar, welcher KL welchen TN beobachten muss. So könnten alle KL sehen, welche Beobachtungen noch ausstehend sind.
> Ein Beispiel: In der Kursplanung ist Bari in der Gruppe von Mikado, somit muss dieser eine Beobachtung zu diesem Block (oder Ausbildungsgefäss) schreiben und es taucht in einer Liste auf, welche Beobachtungen von Mikado noch offen sind.

**Comment by allanbenelli** [comment]
Closed via #146

**Comment by carlobeltrame** [comment]
Nein, die Beobachtungsaufträge waren noch nicht im PR #146, ich muss noch einen dafür eröffnen. Aber Travis failt gerade noch

**Comment by allanbenelli** [comment]
@carlobeltrame Mein Fehler, sorry! Dachte du hast meinen Stand dann übernommen und gleich einfliessen lassen, sorry!
#116 wäre dann aber auch gleich inkludiert, oder?

**Comment by carlobeltrame** [comment]
Korrekt
