### ISSUE TITLE
Verbesserungen am Layout

### ISSUE THREAD

**Issue by carlobeltrame** [gloggi/qualix#14]
* [x] Übertitel in Hochdeutsch
* [x] Entweder home button oder return to home über Logo

**Comment by allanbenelli** [comment]
@carlobeltrame Aso wie gseit, es isch en diskutierbare punkt. ich weiss nöd wie ihrs gsehn :)

**Comment by davudevren** [comment]
Ich denke das cha mer guet na diskutiere, es staht und fallt ned weg de Titel. aber so vergessemers ned 👍
