### ISSUE TITLE
Beobachtungen werde nicht angezeigt

### ISSUE THREAD

**Issue by feigenmann** [gloggi/qualix#145]
Wenn Beobachtungen 2 Personen zugewiesen sind werden sie nicht angezegit.
In Browser developer tools folgende Ausgabe in Console

Source map error: Error: request failed with status 404
Resource URL: http://localhost/js/app.js
Source Map URL: lib.esm.js.map

**Comment by carlobeltrame** [comment]
Kann ich so nicht reproduzieren, bei mir werden auch Multi-TN-Beobachtungen angezeigt.
Der Source Map Error ist nur eine Warnung, und die hat nichts mit Beobachtungen zu tun.
Falls das nochmals auftritt gerne wieder eröffnen und genauere Anweisungen geben, wie man das reproduzieren kann.
