### ISSUE TITLE
Observations not visible

### ISSUE THREAD

**Issue by noahzarro** [gloggi/qualix#148]
Liebes Qualix Team

Wir leiten momentan ein Basiskurs, und nutzen Qualix. Seit eurem einigen Stunden (wahrscheinlich der letzte commit) werden unsere Beobachtungen nicht mehr angezeigt und es ist auch nicht mehr möglich neue zu erfassen. Könnte es sein, dass sich ein Fehler eingeschlichen hat?

Beste Grüsse
Noah Zarro v/o Calmo

**Comment by allanbenelli** [comment]
Ciao Calmo. Erscheinen Fehlermeldungen in der Konsole beim Laden?
Was funktioniert genau nicht? Siehst du einen Teilnehmer, aber einfach unten die Box mit den Beobachtungen nicht mehr? Gleiches beim neuen Beobachtungen erfassen, was passiert da? Bis zu welchem Punkt funktioniert es und dann nicht mehr?

Gruess
Bari

**Comment by carlobeltrame** [comment]
Ciao Calmo

Merci für die Nachricht. Das wird in der Tat mit den neuesten Änderungen zu tun haben. Es hängt aber damit zusammen, dass Browser noch an der "alten" Version festhängen die sie bei sich zwischengespeichert haben. Wenn ihr Qualix z.B. in einem anonymen Browserfenster aufmacht, oder mit Ctrl+F5 die Seite ohne Cache neu ladet müsste es eigentlich wieder gehen.

Sorry für die Umstände, wir müssen in Zukunft besser darauf achten wer gerade in einem Kurs ist wenn wir etwas live schalten.
Gruss, Cosinus

**Comment by noahzarro** [comment]
Ciao Cosinus

Danke viel Mal, es läuft wieder einwandfrei. Euer Tool ist übrigens der Hammer, es erspart einem wahnsinnig viel Arbeit.

Beste Grüsse
Calmo

**Comment by carlobeltrame** [comment]
Kein Problem. Meldet euch gerne wieder falls es nochmals Probleme gibt. Wir planen noch irgendwann diese Woche (bis zu unseren eigenen Kursen) #147 zu mergen, eventuell könnte dann dasselbe "Problem" nochmals auftreten.

Wenn ihr nach dem Kurs noch konkrete Rückmeldungen oder Wünsche für die Zukunft habt wären wir natürlich auch immer gespannt diese zu hören.

Schönen Kurs noch!
