### ISSUE TITLE
Druckansicht Rückmeldung optimieren

### ISSUE THREAD

**Issue by Tschet1** [gloggi/qualix#228]
Bei der Druckansicht der Quali könnte das Layout optimiert werden, damit eine Quali auf möglichst wenigen Seiten Platz hat. Zum Beispiel könnten die Seitenränder verkleinert werden.

**Comment by carlobeltrame** [comment]
Ich habe in #280 mal einen Lösungsansatz umgesetzt. Sehen die dort sichtbaren Ränder besser aus aus deiner Sicht @Tschet1?
