### ISSUE TITLE
Quali: beim einfügen von Beobachtungen bereits eingefügte filtern

### ISSUE THREAD

**Issue by Tschet1** [gloggi/qualix#230]
Das einfügen von Beobachtungen in die Quali würde vereinfacht, wenn es einen (optionalen) Filter geben würde, bei dem nur Beobachtungen angezeigt würden, die noch nicht zur Quali hinzugefügt wurden. Dieser Filter sollte aber auch entfernt werden können, damit eine Beobachtung auch ein 2. Mal eingefügt werden könnte.

**Comment by carlobeltrame** [comment]
Finden wir eine gute Idee. Standardwert sollte am besten eingeschaltet sein (d.h. standardmässig sollen nur Beobachtungen angezeigt werden die noch nicht im Quali sind), und manuell deaktivierbar falls man dann ausnahmsweise doch mal eine Beobachtung ein zweites Mal in demselben Quali verwenden will.
Der Filter sollte zudem wie die anderen Filter auch schon in localStorage persistiert werden.
Dieser spezifische Filter macht nur im Kontext von einem Quali Sinn, auf der Beobachtungsliste einer Person sollte er nicht auftauchen. Dort macht #234 mehr Sinn.
