### ISSUE TITLE
Offene Einladungen können nicht gelöscht werden

### ISSUE THREAD

**Issue by mario-zelger** [gloggi/qualix#232]
Offene Einladungen der Equipe (Kursadmin -> Equipe) können aktuell nicht entfernt werden. Nach der Löschbestätigung folgt ein Redirect auf /course/KURS-NR/admin/invitation/{email}?invitation=EINLADUNG-NR mit dem Inhalt 404 - Nicht gefunden.

**Comment by carlobeltrame** [comment]
Merci für die Meldung! Der Fix wird morgen deployed sein.
