### ISSUE TITLE
Zeichenlimit für TN Freitext erhöhen

### ISSUE THREAD

**Issue by mario-zelger** [gloggi/qualix#247]
Beim Freitext welcher für Teilnehmende definiert werden kann gibt es aktuell das 1023-Zeichenlimit. Hier wäre es hilfreich wenn dieses vergrössert werden könnte.

In unserem Anwendungsfall wollten wir die Empfehlungen der ALs in diese Feld kopieren damit diese direkt einsehbar sind. Je nach Ausführlichkeit überschreitet eine Empfehlung die 1023 Zeichen.

**Comment by carlobeltrame** [comment]
Guter Punkt. In hitobito ist die [Empfehlung](https://github.com/hitobito/hitobito_pbs/blob/master/db/migrate/20150702090243_create_event_approvals.rb#L15) eine TEXT-Spalte in einer MySQL-Datenbank, hat also ein Limit von 65535 Zeichen. Wir sollten das vermutlich in Qualix [gleich](https://laravel.com/docs/9.x/migrations#column-method-text) machen.
