### ISSUE TITLE
Import von TN aus MiData

### ISSUE THREAD

**Issue by carlobeltrame** [gloggi/qualix#54]

**Comment by carlobeltrame** [comment]
Use case Koala:
> die Möglichkeit, Ziele und Teilnehmende zu importieren wäre hilfreich.

Bemerkung: Ziele unter diesem Namen werden momentan nicht in Qualix geführt. Falls Mindestanforderungen gemeint sind, ist uns unklar welches Format wir akzeptieren sollen. Wird momentan nicht umgesetzt bis der Wunsch in präziserer Form weiterhin zu uns kommt.

**Comment by cleverer** [comment]
Allenfalls sind mit Zielen die Empfehlungen aus MiData gemeint. Diese kann man bei den TN bis jetzt ja nicht erfassen.

Falls der Import nicht schon in Entwicklung ist, würde ich mich mal an einen CSV-Importer machen, analog blockimport ecamp…

Als zweiten Schritt könnte ich dann noch die Empfehlungen ins Auge fassen…

**Comment by allanbenelli** [comment]
@cleverer 
Danke für dein Interesse bzw Einsatzbereitschaft. CSV Importer analog blockimport bin ich zur Zeit dran, kommt. 
Meinst du bzgl. dem zweiten Schritt das Importieren oder die Möglichkeit sie zu erfassen?

**Comment by cleverer** [comment]
Beides: erfassen und importieren.

Zur Zeit gibt es auf einem TN nur die Felder Name, Abteilung und Foto.
Deshalb meine Überlegung das erst in einem zweiten Schritt (bzw. in einem separaten Issue) anzugehen. Ich denke das braucht noch Überlegungen wie sinnvoll es ist, wie man es wo integrieren will etc.

**Comment by cleverer** [comment]
Ich sehe gerade, dass dieses separate Issue bereits existiert: #69

**Comment by carlobeltrame** [comment]
@cleverer hast du eine Deadline, bis wann du das Feature in einem Kurs brauchst?

**Comment by cleverer** [comment]
@carlobeltrame nicht konkret, wir können die TN ja auch manuell erfassen.

Wenn wir den Import bis Ende Monat hätten, würde das aber wunderbar auf unsere Frühlingskurse passen.

**Comment by carlobeltrame** [comment]
Sieht bei uns genau gleich aus.
